language: perl
perl:
    - '5.20'
env:
    - BACKEND=moar
matrix:
    fast_finish: true
sudo: false
before_install:
    - git clone https://github.com/tony-o/perl6-travis-bin.git bins
    - mv bins/brew ~/
install:
    - eval "$($HOME/brew/bin/rakudobrew init -)"
    - perl6 -v
script:
    - ls /home/travis/brew/moar-nom/install/share/perl6/sources/C7*
    - prove -e 'perl6 -Ilib' t/
